version: "3"
services:
  nginx:
    image: "docker.io/library/nginx:alpine"
    expose:
        - 80
    labels:
      org.lsdsuite.stats:
    networks:
      - nginx_net
  siege:
    labels:
      org.lsdsuite.stats:
    image: "docker.io/yokogawa/siege"
    command: ["siege", "--concurrent=100", "--delay=1", "--time=50s", "http://tasks.nginx/"]
    networks:
      - nginx_net
#
networks:
  nginx_net:
    driver: overlay
    ipam:
      config:
        - subnet: 10.22.0.0/16
