#!/bin/sh
waste_cpu() {
    while true
    do
#        counter=1
#        while [ $counter -le 1000 ]
#        do
          echo "ola123" | sha256sum
#          counter=$(( $counter + 1 ))
#        done
#        sleep 0.1
    done
}
timeout_child () {
    trap -- "" SIGTERM
    child=$!
    timeout=$1
    (
        sleep $timeout
        kill $child
    ) &
    wait $child
}
waste_cpu & timeout_child $1
