version: '3.4'
services:
  server-1:
    labels:
        # gather detailed stats
        org.lsdsuite.stats: "true"
    image: docker.io/mapa12/bft-smart-experiment:latest
    # image: "docker.io/mapa12/dns-alpine:latest"
    command: bash /source-code/runscripts/startReplicaYCSB.sh
    environment:
      # REPLICA_INDEX={{.Task.Slot}}
      REPLICA_INDEX: 1
      MAX_HEAP_SIZE: 2048M
      # ENV HEAP_NEWSIZE 128M # default
    deploy:
      # FaultSee forces restart_policy to be none anyway
      restart_policy:
          condition: none
      replicas: 0
      placement:
          constraints:
              - node.hostname == faultsee-1
    networks:
      - "backend"

  server-2:
    labels:
        # gather detailed stats
        org.lsdsuite.stats: "true"
    image: docker.io/mapa12/bft-smart-experiment:latest
    command: bash /source-code/runscripts/startReplicaYCSB.sh
    environment:
      # REPLICA_INDEX={{.Task.Slot}}
      REPLICA_INDEX: 2
      MAX_HEAP_SIZE: 2560M
      # ENV HEAP_NEWSIZE 128M # default
    deploy:
        # FaultSee forces restart_policy to be none anyway
        restart_policy:
            condition: none
        replicas: 0
        placement:
            constraints:
                - node.hostname == faultsee-2
    networks:
      - "backend"

  server-3:
    labels:
        # gather detailed stats
        org.lsdsuite.stats: "true"
    image: docker.io/mapa12/bft-smart-experiment:latest
    command: bash /source-code/runscripts/startReplicaYCSB.sh
    environment:
      # REPLICA_INDEX={{.Task.Slot}}
      REPLICA_INDEX: 3
      MAX_HEAP_SIZE: 2560M
      # ENV HEAP_NEWSIZE 128M # default
    deploy:
        # FaultSee forces restart_policy to be none anyway
        restart_policy:
            condition: none
        replicas: 0
        placement:
            constraints:
                - node.hostname == faultsee-3
    networks:
      - "backend"

  server-4:
    labels:
        # gather detailed stats
        org.lsdsuite.stats: "true"
    image: docker.io/mapa12/bft-smart-experiment:latest
    command: bash /source-code/runscripts/startReplicaYCSB.sh
    environment:
      # REPLICA_INDEX={{.Task.Slot}}
      REPLICA_INDEX: 4
      MAX_HEAP_SIZE: 2560M
      # ENV HEAP_NEWSIZE 128M # default
    deploy:
        # FaultSee forces restart_policy to be none anyway
        restart_policy:
            condition: none
        replicas: 0
        placement:
            constraints:
                - node.hostname == faultsee-4
    networks:
      - "backend"

  ycsb-client-load:
    labels:
        # gather detailed stats
        org.lsdsuite.stats: "true"
    image: docker.io/mapa12/bft-smart-experiment:latest
    command: bash /source-code/runscripts/start-ycsb-client.sh
    environment:
        ACTION: load
        RECNUM: 100000
        OPNUM:  125000
    deploy:
        restart_policy:
            condition: none
        replicas: 0
        placement:
            constraints:
                - node.hostname == faultsee-5
    networks:
      - "backend"

  ycsb-client-run:
    labels:
        # gather detailed stats
        org.lsdsuite.stats: "true"
    image: docker.io/mapa12/bft-smart-experiment:latest
    command: bash /source-code/runscripts/start-ycsb-client.sh
    environment:
        ACTION: run
        THREADS: 10
        RECNUM: 100000
        OPNUM:  4000000

        # allow to run multiple docker images,
        # each will have a different start client id
        # if two clients with the same id try to connect an error ensues
        START_CLIEND_ID: "{{.Task.Slot}}"
    deploy:
        restart_policy:
            condition: none
        replicas: 0
        placement:
            constraints:
                - node.hostname == faultsee-5
    networks:
      - "backend"

networks:
  backend:
    driver: overlay
    ipam:
      config:
        - subnet: 10.22.0.0/16

# export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
